FROM python:3.12.4-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir uv


WORKDIR /app

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-dev

COPY predict.py pipeline_v2.bin ./

EXPOSE 9696

CMD ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9696"]

